# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_card_name', models.CharField(max_length=100)),
                ('gift_card_discription', models.TextField()),
                ('gift_card_image', models.CharField(max_length=100)),
                ('gift_card_price', models.CharField(max_length=10)),
            ],
        ),
    ]
